api/urls.py
from django.urls import path

# from api.views import BookReviewDetailAPIView, BookReviewsApiView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet, ProfileUpdateViewSet, LoginAPIView, RegistrationAPIView, LogoutAPIView

app_name = "api"
router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename='review')
router.register(r'profile-update', ProfileUpdateViewSet, basename='profile-update')


urlpatterns = [
    path('login/', LoginAPIView.as_view(), name='login-api'),
    path('register/', RegistrationAPIView.as_view(), name='register-api'),
    path('logout/', LogoutAPIView.as_view(), name="logout-api")
]

urlpatterns += router.urls

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, home_page

urlpatterns = [
    path("", landing_page, name="landing_page"),
    path("home/", home_page, name="home_page"),
    path("users/", include("users.urls")),
    path("books/", include("books.urls")),
    path("api/", include("api.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, ProfileVIew, LogoutView, ProfileUpdateView


app_name = "users"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileVIew.as_view(), name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile-edit")
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="default_profile_pic.png")
    phone_number = models.CharField(max_length=9, blank=True, null=True)

users/forms.py
from django import forms


from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user


# profile update form
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture')

users/views.py
from django.contrib import messages
from django.contrib.auth import logout, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from users.forms import UserCreateForm, UserUpdateForm


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            "form": create_form
        }
        return render(request, "users/register.html", context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
            "form": create_form
        }
            return render(request, "users/register.html", context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()

        return render(request, "users/login.html", {"login_form": login_form})

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            users = login_form.get_user()
            login(request, users)

            messages.success(request, "You have to succsefull logged in.")

            return redirect("books:list")
        else:
            return render(request, "users/login.html", {"login_form": login_form})


# profile view
class ProfileVIew(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "users/profile.html", {"user": request.user})


# logout view
class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect("landing_page")


# profile update view
class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)

        return render(request, "users/profile_edit.html", {"form": user_update_form})

    def post(self, request):
        user_update_form = UserUpdateForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
        )

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, "You have successfully updated your profile")

            return redirect("users:profile")

        return render(request, "users/profile_edit.html", {"form": user_update_form})

users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
    {% block title %}Login {% endblock %}

    {% block content %}
    <h3>Login</h3>

    <div class="row">
        <div class="col-4">
            <form method="post">
        {% csrf_token %}
        {{ login_form|crispy}}

        <button class="btn btn-primary">Login</button>  <span class="ms-3">No account?   <a href="{% url 'users:register' %}">Create your account</a></span>
        </form>
        </div>
    </div>


    {% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% block title %}Profile page{% endblock %}
{% block content %}
    <h3>Profile</h3>

<div class=" image d-flex flex-column justify-content-center align-items-center">
    <button class="btn btn-secondary">
    <img class="profile-pic" src="{{ user.profile_picture.url }}" alt="Profile picture">
    </button>
    <span class="name mt-3">{{ user.first_name }}</span> <span class="idd">{{ user.last_name }}</span>
    <span class="idd">{{ user.username }}</span>
    <span class="idd">{{ user.email }}</span>
    <div class="d-flex flex-row justify-content-center align-items-center gap-2">
    <div class=" d-flex mt-2"> <a class="btn btn-dark" href="{% url 'users:profile-edit' %}">edit profile</a> </div>
    <div class=" px-2 rounded mt-4 date "> <span class="join">Joined {{ user.date_joined |date:"M d, Y" }}</span>
    </div>
</div>
</div>


{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h3>edit profile</h3>

    <div class="row">
        <div class="col-4">
            <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form|crispy }}

        <button class="btn btn-primary">Save changes</button>
    </form>

        </div>
    </div>

{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Register{% endblock %}
{% block content %}
<h3>Register </h3>

<div class="row">
    <div class="col-4">
        <form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
    </div>
</div>


{% endblock %}